### ISSUE TITLE
Package icons in package list, commit, summary (and more)?

### ISSUE THREAD

**Issue by perrsona1234** [shundhammer/yqpkg#20]
Hi.

I'm not a developer or anything, just had an idea while looking at the screenshots. Would it be possible to add package icons to package list, commit and summary? They already exist and are shown in patterns and in package descriptions.

So, for example, in the package list, instead of:

✅ Package-name This is a package description.
✅ MozillaFirefox Mozilla Firefox Web Browser
✅ dejavu-fonts DejaVu Truetype Fonts
✅ man-pages Linux Manual Pages
✅ glibc Standard Shared Libraries (from the GNU C Library)

It would be:

✅ Icon Package-name This is a package description.
✅ 🦊 MozillaFirefox Mozilla Firefox Web Browser
✅ 📜 dejavu-fonts DejaVu Truetype Fonts
✅ 📖 man-pages Linux Manual Pages
✅ 📦 glibc Standard Shared Libraries (from the GNU C Library)

And more icons could be added for packages that have, for example, patches or upgrades (📤) available, need to be downgraded (📥), etc. I'm talking here about these icons being before the version number, instead of that number just being in a different color.

So, for example, in the package list, instead of:

Current-package-version (new/old-package-version)
24.08-1.1 (24.09-1.1)
24.08-1.1 (24.07-1.1)

It would be:
Current-package-version (📤 new/📥 old-package-version)
24.08-1.1 (📤 24.09-1.1)
24.08-1.1 (📥 24.07-1.1)

Of course, emojis used here are just to demonstrate the idea. Perhaps some pattern icons could be reused for this? For DE-specific packages, docs packages? For libraries maybe the general icon for an .rpm file?

That would be all, I think.
Thanks for everything you do.
Have a good day/night.

**Comment by shundhammer** [comment]
Many things are possible, and I would like some more eye candy. Some of what you propose is already there: For example the application icons for certain packages like Firefox or Thunderbird in the package description view below the package list:

![yqpkg-mozilla](https://github.com/user-attachments/assets/275385c5-e0f1-431c-be55-ce2cf2c1f921)

But it's a fine line between catchy eye candy and overwhelming the user with visual cues, and preferences vary between users: Some like it, some don't.

In a good GUI, colors and especially colored icons are used sparingly, because those things cry out "click me!!!" to the user; at the very least, they signal some importance. If that is overdone, that tool is lost, and users become immune against such attention-seeking.

That's one reason (apart from technical issues) why the only graphical thing in the package list is the status icon of each package. Already in the patterns list (which is very similar), this is on the verge of going overboard:

![yqpkg-patterns](https://github.com/user-attachments/assets/899b81ad-0514-4877-be36-1f75c9095a94)

Technically, that list on the left with the software patterns is closely related to the package list on the right. But do you even _see_ the status icons on the very left of the patterns, or don't the colorful pattern icons grab so much of your attention that you tend to ignore that little checkbox at each pattern? And in this screenshot, we happen to also have the "fileroller" package selected which has its own icon in the bottom "Description" view.

This screen is crowded with information, and it's already overloaded with visual cues.  Now imagine what it would look like with packages getting their own application icon in the package list, too. You'd be drowned in color and attention-grabbing. Usability would greatly suffer.

The main task of this whole screen is to let the user select things; in this view, patterns as well as individual packages, in other views just packages.

But we have even more vidual cues with colors:

![yqpkg-new-pkg](https://github.com/user-attachments/assets/6076776c-5a68-45f8-9f91-19641faceb08)

In the "Repositories" view, we have the "@System" pseudo-repo which represents your installed system; you see all the packages that you have installed. When you click on the "Version" column of the package list, it sorts by version; and the first sort criterion is the relation between the installed version vs. the available version. The color in that column gives a hint (you may have to click twice to see it at the start of the list):

- Red: Installed is newer than available, or there is no available version (i.e. the package is orphaned; no repo provides that package anymore)
- Blue: There is a newer available version than the installed one, i.e. that package could be updated.
- Black: There is no newer version than the installed one; no update for this package right now.

That is important information, and it should not be drowned out by even more colorful GUI elements.

**Comment by shundhammer** [comment]
Having said all that, a little more eye candy would be most welcome; for example in the page headers of the commit and summary pages. But that would need some help from a graphics designer to find (or create) good icons.

But in the lists of the commit page, for example, I would not add many more icons because that could easily drown out the "Download ongoing" or "Download done" icons. Maybe an icon for packages that are to be removed; right now, they get only a very subtle visual hint with a minus sign prefix:  "- oldeditor" vs. "neweditor" without anything for packages that are installed or updated. And since installing or updating is the much more common operation, the normal thing, they don't get an additional visual cue.

And since for a package that is removed there is no download, that also does not clash with the download icons.

Yes, all that were deliberate thoughts that went into that very simplistic display. True elegance in a good user interface is not in adding more and more elements, but to omit elements until nothing can be omitted anymore without loss.

For a while I had considered adding the task type to each list element on the commit page; a different icon for each of "install", "update", "remove" and maybe one more icon for "explicitly requested by the user" or "needed by dependencies". Or combining them into 6 different icons.

But think about it: It would be in addition to the existing "download" icons which already consist of two sub-icons: one for the download itself, and the check mark (or its absence) indicating if the download is still ongoing or already finished.

And now think about the possible permutations:
- Install / Update / Remove
- by user / by dependency
- download (or not)
- download finished (or not) check mark

That would be up to 4 graphical elements for each list item. That would be completely over the top.

And no, omitting the task type and requester in the downloads list would not be a good approach; the task would alter its shape as it moves through the lists. Not good.

You see, it's all a lot more complicated than it appears at first glance. ;-)
