### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by victorhck** [shundhammer/yqpkg#21]
I want to try this ne package, but can't compile in my Tumbleweed machine with Plasma desktop:

```
$ make -f Makefile.repo                                                                                        
rm -rf build
mkdir build; \
cd build; \
cmake ..
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_INSTALL_PREFIX: /usr
CMake Error at src/CMakeLists.txt:17 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
make: *** [Makefile.repo:21: configure] Error 1

```

You should add in READMe that make, cmake, gcc-c++, etc...       is needed to compile

Greetings.

**Comment by shundhammer** [comment]
You need to install the Qt development packages. The .spec file in the `package/` subdirectory gives some hints:

```console
[sh @ balrog] .../work/src/yqpkg 103 % grep 'BuildRequires' package/*.spec
BuildRequires:  boost-devel
BuildRequires:  cmake >= 3.17
BuildRequires:  gcc-c++
BuildRequires:  gcc-fortran
BuildRequires:  libboost_test-devel
BuildRequires:  pkg-config
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  %{libzypp_devel_version}
```

Basically what `CMake` wanted to tell you, but of course they never tell you what concrete _packages_ you need to install. _I hate CMake with a passion_.

But hey, we now have a tool for that - even as a non-root user... (well, you don't have it yet, but I do):

![qt5-devel-pkg](https://github.com/user-attachments/assets/ce64f71c-cf81-4b2b-8c55-48019fca7218)

The naming of those Qt packages is - _creative_. Unfortunately. So let's start with

```
sudo zypper in libQt5Core-devel libQt5Gui-devel libQt5Widgets-devel libzypp-devel boost-devel
```

**Comment by shundhammer** [comment]
BTW that weird package naming is one big reason why I go for `yast2 sw_single` or now for `yqpkg`. Try puzzling that stuff together with `zypper` commands.

**Comment by shundhammer** [comment]
Alternatively, use `yast2 sw_single` to install patterns "C/C++ Development" and "Qt 5 Development".

**Comment by shundhammer** [comment]
Please let me know if this worked.

**Comment by victorhck** [comment]
too many packages to install, just to test...

For the record: an user has been compiled the packahe in OBS and from that you get a single rpm just to install and test:

https://software.opensuse.org/download/package?package=yqpkg&project=home%3Aecsos

**Comment by shundhammer** [comment]
OK, thank you; that's good to know. I didn't get around yet to do that, but I intended to provide a Git version in parallel to a stable version for this project, just like with my QDirStat: 

https://build.opensuse.org/project/subprojects/home:shundhammer

I haven't even tried out that `yqpkg.spec` file from the project's `package/` subdirectory. In theory, it should work, but my experiences in the past since late 1999 show that it's never that easy; it always needs several iterations with changes to the .spec file.

And then of course there is the constant work to trigger that source service to actually build the package (it grabs the sources from GitHub, checks them into OBS (the openSUSE Build Service) and builds them. Still, it needs some human interaction every now and them to monitor the whole process and to fix build problems with the various distributions (Factory and the latest Leap 15.x) and architectures (x86_64, ppc64, aarch64).
